import { describe, expectTypeOf, it } from "vitest";

/**
 * `Env` is hand-written, `BaseEnv` is regenerated by `wrangler types`. The one
 * failure mode that matters is the two drifting apart silently: if the extends
 * clause is lost, `Env` still resolves everywhere and every binding on it
 * quietly becomes `any`.
 */
describe("service-bindings.d.ts", () => {
	it("resolves Env as a real type, not any", () => {
		expectTypeOf<Env>().not.toBeAny();
	});

	it("carries the bindings wrangler generates onto BaseEnv", () => {
		expectTypeOf<Env>().toExtend<BaseEnv>();
		expectTypeOf<Env["DATABASE_HOST"]>().toEqualTypeOf<string>();
		expectTypeOf<Env["RATE_LIMITER_MUTATIONS"]>().not.toBeAny();
	});
});
