/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthDashboardRouteRouteImport } from './routes/_auth/dashboard/route'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthDashboardDirectRouteRouteImport } from './routes/_auth/dashboard/direct/route'
import { Route as AuthDashboardBindingRouteRouteImport } from './routes/_auth/dashboard/binding/route'
import { Route as AuthDashboardApiRouteRouteImport } from './routes/_auth/dashboard/api/route'
import { Route as AuthDashboardDirectIndexRouteImport } from './routes/_auth/dashboard/direct/index'
import { Route as AuthDashboardBindingIndexRouteImport } from './routes/_auth/dashboard/binding/index'
import { Route as AuthDashboardApiIndexRouteImport } from './routes/_auth/dashboard/api/index'
import { Route as AuthDashboardDirectUpdateRouteImport } from './routes/_auth/dashboard/direct/update'
import { Route as AuthDashboardDirectReadRouteImport } from './routes/_auth/dashboard/direct/read'
import { Route as AuthDashboardDirectListRouteImport } from './routes/_auth/dashboard/direct/list'
import { Route as AuthDashboardDirectDeleteRouteImport } from './routes/_auth/dashboard/direct/delete'
import { Route as AuthDashboardDirectCreateRouteImport } from './routes/_auth/dashboard/direct/create'
import { Route as AuthDashboardBindingUpdateRouteImport } from './routes/_auth/dashboard/binding/update'
import { Route as AuthDashboardBindingReadRouteImport } from './routes/_auth/dashboard/binding/read'
import { Route as AuthDashboardBindingListRouteImport } from './routes/_auth/dashboard/binding/list'
import { Route as AuthDashboardBindingDeleteRouteImport } from './routes/_auth/dashboard/binding/delete'
import { Route as AuthDashboardBindingCreateRouteImport } from './routes/_auth/dashboard/binding/create'
import { Route as AuthDashboardApiUpdateRouteImport } from './routes/_auth/dashboard/api/update'
import { Route as AuthDashboardApiReadRouteImport } from './routes/_auth/dashboard/api/read'
import { Route as AuthDashboardApiListRouteImport } from './routes/_auth/dashboard/api/list'
import { Route as AuthDashboardApiDeleteRouteImport } from './routes/_auth/dashboard/api/delete'
import { Route as AuthDashboardApiCreateRouteImport } from './routes/_auth/dashboard/api/create'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRouteRoute = AuthDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardDirectRouteRoute =
  AuthDashboardDirectRouteRouteImport.update({
    id: '/direct',
    path: '/direct',
    getParentRoute: () => AuthDashboardRouteRoute,
  } as any)
const AuthDashboardBindingRouteRoute =
  AuthDashboardBindingRouteRouteImport.update({
    id: '/binding',
    path: '/binding',
    getParentRoute: () => AuthDashboardRouteRoute,
  } as any)
const AuthDashboardApiRouteRoute = AuthDashboardApiRouteRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardDirectIndexRoute =
  AuthDashboardDirectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthDashboardDirectRouteRoute,
  } as any)
const AuthDashboardBindingIndexRoute =
  AuthDashboardBindingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthDashboardBindingRouteRoute,
  } as any)
const AuthDashboardApiIndexRoute = AuthDashboardApiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardApiRouteRoute,
} as any)
const AuthDashboardDirectUpdateRoute =
  AuthDashboardDirectUpdateRouteImport.update({
    id: '/update',
    path: '/update',
    getParentRoute: () => AuthDashboardDirectRouteRoute,
  } as any)
const AuthDashboardDirectReadRoute = AuthDashboardDirectReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => AuthDashboardDirectRouteRoute,
} as any)
const AuthDashboardDirectListRoute = AuthDashboardDirectListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AuthDashboardDirectRouteRoute,
} as any)
const AuthDashboardDirectDeleteRoute =
  AuthDashboardDirectDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => AuthDashboardDirectRouteRoute,
  } as any)
const AuthDashboardDirectCreateRoute =
  AuthDashboardDirectCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthDashboardDirectRouteRoute,
  } as any)
const AuthDashboardBindingUpdateRoute =
  AuthDashboardBindingUpdateRouteImport.update({
    id: '/update',
    path: '/update',
    getParentRoute: () => AuthDashboardBindingRouteRoute,
  } as any)
const AuthDashboardBindingReadRoute =
  AuthDashboardBindingReadRouteImport.update({
    id: '/read',
    path: '/read',
    getParentRoute: () => AuthDashboardBindingRouteRoute,
  } as any)
const AuthDashboardBindingListRoute =
  AuthDashboardBindingListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AuthDashboardBindingRouteRoute,
  } as any)
const AuthDashboardBindingDeleteRoute =
  AuthDashboardBindingDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => AuthDashboardBindingRouteRoute,
  } as any)
const AuthDashboardBindingCreateRoute =
  AuthDashboardBindingCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthDashboardBindingRouteRoute,
  } as any)
const AuthDashboardApiUpdateRoute = AuthDashboardApiUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => AuthDashboardApiRouteRoute,
} as any)
const AuthDashboardApiReadRoute = AuthDashboardApiReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => AuthDashboardApiRouteRoute,
} as any)
const AuthDashboardApiListRoute = AuthDashboardApiListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AuthDashboardApiRouteRoute,
} as any)
const AuthDashboardApiDeleteRoute = AuthDashboardApiDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => AuthDashboardApiRouteRoute,
} as any)
const AuthDashboardApiCreateRoute = AuthDashboardApiCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthDashboardApiRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/dashboard/api': typeof AuthDashboardApiRouteRouteWithChildren
  '/dashboard/binding': typeof AuthDashboardBindingRouteRouteWithChildren
  '/dashboard/direct': typeof AuthDashboardDirectRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/dashboard/api/create': typeof AuthDashboardApiCreateRoute
  '/dashboard/api/delete': typeof AuthDashboardApiDeleteRoute
  '/dashboard/api/list': typeof AuthDashboardApiListRoute
  '/dashboard/api/read': typeof AuthDashboardApiReadRoute
  '/dashboard/api/update': typeof AuthDashboardApiUpdateRoute
  '/dashboard/binding/create': typeof AuthDashboardBindingCreateRoute
  '/dashboard/binding/delete': typeof AuthDashboardBindingDeleteRoute
  '/dashboard/binding/list': typeof AuthDashboardBindingListRoute
  '/dashboard/binding/read': typeof AuthDashboardBindingReadRoute
  '/dashboard/binding/update': typeof AuthDashboardBindingUpdateRoute
  '/dashboard/direct/create': typeof AuthDashboardDirectCreateRoute
  '/dashboard/direct/delete': typeof AuthDashboardDirectDeleteRoute
  '/dashboard/direct/list': typeof AuthDashboardDirectListRoute
  '/dashboard/direct/read': typeof AuthDashboardDirectReadRoute
  '/dashboard/direct/update': typeof AuthDashboardDirectUpdateRoute
  '/dashboard/api/': typeof AuthDashboardApiIndexRoute
  '/dashboard/binding/': typeof AuthDashboardBindingIndexRoute
  '/dashboard/direct/': typeof AuthDashboardDirectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/dashboard/api/create': typeof AuthDashboardApiCreateRoute
  '/dashboard/api/delete': typeof AuthDashboardApiDeleteRoute
  '/dashboard/api/list': typeof AuthDashboardApiListRoute
  '/dashboard/api/read': typeof AuthDashboardApiReadRoute
  '/dashboard/api/update': typeof AuthDashboardApiUpdateRoute
  '/dashboard/binding/create': typeof AuthDashboardBindingCreateRoute
  '/dashboard/binding/delete': typeof AuthDashboardBindingDeleteRoute
  '/dashboard/binding/list': typeof AuthDashboardBindingListRoute
  '/dashboard/binding/read': typeof AuthDashboardBindingReadRoute
  '/dashboard/binding/update': typeof AuthDashboardBindingUpdateRoute
  '/dashboard/direct/create': typeof AuthDashboardDirectCreateRoute
  '/dashboard/direct/delete': typeof AuthDashboardDirectDeleteRoute
  '/dashboard/direct/list': typeof AuthDashboardDirectListRoute
  '/dashboard/direct/read': typeof AuthDashboardDirectReadRoute
  '/dashboard/direct/update': typeof AuthDashboardDirectUpdateRoute
  '/dashboard/api': typeof AuthDashboardApiIndexRoute
  '/dashboard/binding': typeof AuthDashboardBindingIndexRoute
  '/dashboard/direct': typeof AuthDashboardDirectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_auth/dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/_auth/dashboard/api': typeof AuthDashboardApiRouteRouteWithChildren
  '/_auth/dashboard/binding': typeof AuthDashboardBindingRouteRouteWithChildren
  '/_auth/dashboard/direct': typeof AuthDashboardDirectRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/dashboard/api/create': typeof AuthDashboardApiCreateRoute
  '/_auth/dashboard/api/delete': typeof AuthDashboardApiDeleteRoute
  '/_auth/dashboard/api/list': typeof AuthDashboardApiListRoute
  '/_auth/dashboard/api/read': typeof AuthDashboardApiReadRoute
  '/_auth/dashboard/api/update': typeof AuthDashboardApiUpdateRoute
  '/_auth/dashboard/binding/create': typeof AuthDashboardBindingCreateRoute
  '/_auth/dashboard/binding/delete': typeof AuthDashboardBindingDeleteRoute
  '/_auth/dashboard/binding/list': typeof AuthDashboardBindingListRoute
  '/_auth/dashboard/binding/read': typeof AuthDashboardBindingReadRoute
  '/_auth/dashboard/binding/update': typeof AuthDashboardBindingUpdateRoute
  '/_auth/dashboard/direct/create': typeof AuthDashboardDirectCreateRoute
  '/_auth/dashboard/direct/delete': typeof AuthDashboardDirectDeleteRoute
  '/_auth/dashboard/direct/list': typeof AuthDashboardDirectListRoute
  '/_auth/dashboard/direct/read': typeof AuthDashboardDirectReadRoute
  '/_auth/dashboard/direct/update': typeof AuthDashboardDirectUpdateRoute
  '/_auth/dashboard/api/': typeof AuthDashboardApiIndexRoute
  '/_auth/dashboard/binding/': typeof AuthDashboardBindingIndexRoute
  '/_auth/dashboard/direct/': typeof AuthDashboardDirectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/api/health'
    | '/dashboard/api'
    | '/dashboard/binding'
    | '/dashboard/direct'
    | '/api/auth/$'
    | '/app/'
    | '/dashboard/'
    | '/dashboard/api/create'
    | '/dashboard/api/delete'
    | '/dashboard/api/list'
    | '/dashboard/api/read'
    | '/dashboard/api/update'
    | '/dashboard/binding/create'
    | '/dashboard/binding/delete'
    | '/dashboard/binding/list'
    | '/dashboard/binding/read'
    | '/dashboard/binding/update'
    | '/dashboard/direct/create'
    | '/dashboard/direct/delete'
    | '/dashboard/direct/list'
    | '/dashboard/direct/read'
    | '/dashboard/direct/update'
    | '/dashboard/api/'
    | '/dashboard/binding/'
    | '/dashboard/direct/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/api/health'
    | '/api/auth/$'
    | '/app'
    | '/dashboard'
    | '/dashboard/api/create'
    | '/dashboard/api/delete'
    | '/dashboard/api/list'
    | '/dashboard/api/read'
    | '/dashboard/api/update'
    | '/dashboard/binding/create'
    | '/dashboard/binding/delete'
    | '/dashboard/binding/list'
    | '/dashboard/binding/read'
    | '/dashboard/binding/update'
    | '/dashboard/direct/create'
    | '/dashboard/direct/delete'
    | '/dashboard/direct/list'
    | '/dashboard/direct/read'
    | '/dashboard/direct/update'
    | '/dashboard/api'
    | '/dashboard/binding'
    | '/dashboard/direct'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/signin'
    | '/signup'
    | '/_auth/dashboard'
    | '/api/health'
    | '/_auth/dashboard/api'
    | '/_auth/dashboard/binding'
    | '/_auth/dashboard/direct'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/dashboard/'
    | '/_auth/dashboard/api/create'
    | '/_auth/dashboard/api/delete'
    | '/_auth/dashboard/api/list'
    | '/_auth/dashboard/api/read'
    | '/_auth/dashboard/api/update'
    | '/_auth/dashboard/binding/create'
    | '/_auth/dashboard/binding/delete'
    | '/_auth/dashboard/binding/list'
    | '/_auth/dashboard/binding/read'
    | '/_auth/dashboard/binding/update'
    | '/_auth/dashboard/direct/create'
    | '/_auth/dashboard/direct/delete'
    | '/_auth/dashboard/direct/list'
    | '/_auth/dashboard/direct/read'
    | '/_auth/dashboard/direct/update'
    | '/_auth/dashboard/api/'
    | '/_auth/dashboard/binding/'
    | '/_auth/dashboard/direct/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard/direct': {
      id: '/_auth/dashboard/direct'
      path: '/direct'
      fullPath: '/dashboard/direct'
      preLoaderRoute: typeof AuthDashboardDirectRouteRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/binding': {
      id: '/_auth/dashboard/binding'
      path: '/binding'
      fullPath: '/dashboard/binding'
      preLoaderRoute: typeof AuthDashboardBindingRouteRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/api': {
      id: '/_auth/dashboard/api'
      path: '/api'
      fullPath: '/dashboard/api'
      preLoaderRoute: typeof AuthDashboardApiRouteRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/direct/': {
      id: '/_auth/dashboard/direct/'
      path: '/'
      fullPath: '/dashboard/direct/'
      preLoaderRoute: typeof AuthDashboardDirectIndexRouteImport
      parentRoute: typeof AuthDashboardDirectRouteRoute
    }
    '/_auth/dashboard/binding/': {
      id: '/_auth/dashboard/binding/'
      path: '/'
      fullPath: '/dashboard/binding/'
      preLoaderRoute: typeof AuthDashboardBindingIndexRouteImport
      parentRoute: typeof AuthDashboardBindingRouteRoute
    }
    '/_auth/dashboard/api/': {
      id: '/_auth/dashboard/api/'
      path: '/'
      fullPath: '/dashboard/api/'
      preLoaderRoute: typeof AuthDashboardApiIndexRouteImport
      parentRoute: typeof AuthDashboardApiRouteRoute
    }
    '/_auth/dashboard/direct/update': {
      id: '/_auth/dashboard/direct/update'
      path: '/update'
      fullPath: '/dashboard/direct/update'
      preLoaderRoute: typeof AuthDashboardDirectUpdateRouteImport
      parentRoute: typeof AuthDashboardDirectRouteRoute
    }
    '/_auth/dashboard/direct/read': {
      id: '/_auth/dashboard/direct/read'
      path: '/read'
      fullPath: '/dashboard/direct/read'
      preLoaderRoute: typeof AuthDashboardDirectReadRouteImport
      parentRoute: typeof AuthDashboardDirectRouteRoute
    }
    '/_auth/dashboard/direct/list': {
      id: '/_auth/dashboard/direct/list'
      path: '/list'
      fullPath: '/dashboard/direct/list'
      preLoaderRoute: typeof AuthDashboardDirectListRouteImport
      parentRoute: typeof AuthDashboardDirectRouteRoute
    }
    '/_auth/dashboard/direct/delete': {
      id: '/_auth/dashboard/direct/delete'
      path: '/delete'
      fullPath: '/dashboard/direct/delete'
      preLoaderRoute: typeof AuthDashboardDirectDeleteRouteImport
      parentRoute: typeof AuthDashboardDirectRouteRoute
    }
    '/_auth/dashboard/direct/create': {
      id: '/_auth/dashboard/direct/create'
      path: '/create'
      fullPath: '/dashboard/direct/create'
      preLoaderRoute: typeof AuthDashboardDirectCreateRouteImport
      parentRoute: typeof AuthDashboardDirectRouteRoute
    }
    '/_auth/dashboard/binding/update': {
      id: '/_auth/dashboard/binding/update'
      path: '/update'
      fullPath: '/dashboard/binding/update'
      preLoaderRoute: typeof AuthDashboardBindingUpdateRouteImport
      parentRoute: typeof AuthDashboardBindingRouteRoute
    }
    '/_auth/dashboard/binding/read': {
      id: '/_auth/dashboard/binding/read'
      path: '/read'
      fullPath: '/dashboard/binding/read'
      preLoaderRoute: typeof AuthDashboardBindingReadRouteImport
      parentRoute: typeof AuthDashboardBindingRouteRoute
    }
    '/_auth/dashboard/binding/list': {
      id: '/_auth/dashboard/binding/list'
      path: '/list'
      fullPath: '/dashboard/binding/list'
      preLoaderRoute: typeof AuthDashboardBindingListRouteImport
      parentRoute: typeof AuthDashboardBindingRouteRoute
    }
    '/_auth/dashboard/binding/delete': {
      id: '/_auth/dashboard/binding/delete'
      path: '/delete'
      fullPath: '/dashboard/binding/delete'
      preLoaderRoute: typeof AuthDashboardBindingDeleteRouteImport
      parentRoute: typeof AuthDashboardBindingRouteRoute
    }
    '/_auth/dashboard/binding/create': {
      id: '/_auth/dashboard/binding/create'
      path: '/create'
      fullPath: '/dashboard/binding/create'
      preLoaderRoute: typeof AuthDashboardBindingCreateRouteImport
      parentRoute: typeof AuthDashboardBindingRouteRoute
    }
    '/_auth/dashboard/api/update': {
      id: '/_auth/dashboard/api/update'
      path: '/update'
      fullPath: '/dashboard/api/update'
      preLoaderRoute: typeof AuthDashboardApiUpdateRouteImport
      parentRoute: typeof AuthDashboardApiRouteRoute
    }
    '/_auth/dashboard/api/read': {
      id: '/_auth/dashboard/api/read'
      path: '/read'
      fullPath: '/dashboard/api/read'
      preLoaderRoute: typeof AuthDashboardApiReadRouteImport
      parentRoute: typeof AuthDashboardApiRouteRoute
    }
    '/_auth/dashboard/api/list': {
      id: '/_auth/dashboard/api/list'
      path: '/list'
      fullPath: '/dashboard/api/list'
      preLoaderRoute: typeof AuthDashboardApiListRouteImport
      parentRoute: typeof AuthDashboardApiRouteRoute
    }
    '/_auth/dashboard/api/delete': {
      id: '/_auth/dashboard/api/delete'
      path: '/delete'
      fullPath: '/dashboard/api/delete'
      preLoaderRoute: typeof AuthDashboardApiDeleteRouteImport
      parentRoute: typeof AuthDashboardApiRouteRoute
    }
    '/_auth/dashboard/api/create': {
      id: '/_auth/dashboard/api/create'
      path: '/create'
      fullPath: '/dashboard/api/create'
      preLoaderRoute: typeof AuthDashboardApiCreateRouteImport
      parentRoute: typeof AuthDashboardApiRouteRoute
    }
  }
}

interface AuthDashboardApiRouteRouteChildren {
  AuthDashboardApiCreateRoute: typeof AuthDashboardApiCreateRoute
  AuthDashboardApiDeleteRoute: typeof AuthDashboardApiDeleteRoute
  AuthDashboardApiListRoute: typeof AuthDashboardApiListRoute
  AuthDashboardApiReadRoute: typeof AuthDashboardApiReadRoute
  AuthDashboardApiUpdateRoute: typeof AuthDashboardApiUpdateRoute
  AuthDashboardApiIndexRoute: typeof AuthDashboardApiIndexRoute
}

const AuthDashboardApiRouteRouteChildren: AuthDashboardApiRouteRouteChildren = {
  AuthDashboardApiCreateRoute: AuthDashboardApiCreateRoute,
  AuthDashboardApiDeleteRoute: AuthDashboardApiDeleteRoute,
  AuthDashboardApiListRoute: AuthDashboardApiListRoute,
  AuthDashboardApiReadRoute: AuthDashboardApiReadRoute,
  AuthDashboardApiUpdateRoute: AuthDashboardApiUpdateRoute,
  AuthDashboardApiIndexRoute: AuthDashboardApiIndexRoute,
}

const AuthDashboardApiRouteRouteWithChildren =
  AuthDashboardApiRouteRoute._addFileChildren(
    AuthDashboardApiRouteRouteChildren,
  )

interface AuthDashboardBindingRouteRouteChildren {
  AuthDashboardBindingCreateRoute: typeof AuthDashboardBindingCreateRoute
  AuthDashboardBindingDeleteRoute: typeof AuthDashboardBindingDeleteRoute
  AuthDashboardBindingListRoute: typeof AuthDashboardBindingListRoute
  AuthDashboardBindingReadRoute: typeof AuthDashboardBindingReadRoute
  AuthDashboardBindingUpdateRoute: typeof AuthDashboardBindingUpdateRoute
  AuthDashboardBindingIndexRoute: typeof AuthDashboardBindingIndexRoute
}

const AuthDashboardBindingRouteRouteChildren: AuthDashboardBindingRouteRouteChildren =
  {
    AuthDashboardBindingCreateRoute: AuthDashboardBindingCreateRoute,
    AuthDashboardBindingDeleteRoute: AuthDashboardBindingDeleteRoute,
    AuthDashboardBindingListRoute: AuthDashboardBindingListRoute,
    AuthDashboardBindingReadRoute: AuthDashboardBindingReadRoute,
    AuthDashboardBindingUpdateRoute: AuthDashboardBindingUpdateRoute,
    AuthDashboardBindingIndexRoute: AuthDashboardBindingIndexRoute,
  }

const AuthDashboardBindingRouteRouteWithChildren =
  AuthDashboardBindingRouteRoute._addFileChildren(
    AuthDashboardBindingRouteRouteChildren,
  )

interface AuthDashboardDirectRouteRouteChildren {
  AuthDashboardDirectCreateRoute: typeof AuthDashboardDirectCreateRoute
  AuthDashboardDirectDeleteRoute: typeof AuthDashboardDirectDeleteRoute
  AuthDashboardDirectListRoute: typeof AuthDashboardDirectListRoute
  AuthDashboardDirectReadRoute: typeof AuthDashboardDirectReadRoute
  AuthDashboardDirectUpdateRoute: typeof AuthDashboardDirectUpdateRoute
  AuthDashboardDirectIndexRoute: typeof AuthDashboardDirectIndexRoute
}

const AuthDashboardDirectRouteRouteChildren: AuthDashboardDirectRouteRouteChildren =
  {
    AuthDashboardDirectCreateRoute: AuthDashboardDirectCreateRoute,
    AuthDashboardDirectDeleteRoute: AuthDashboardDirectDeleteRoute,
    AuthDashboardDirectListRoute: AuthDashboardDirectListRoute,
    AuthDashboardDirectReadRoute: AuthDashboardDirectReadRoute,
    AuthDashboardDirectUpdateRoute: AuthDashboardDirectUpdateRoute,
    AuthDashboardDirectIndexRoute: AuthDashboardDirectIndexRoute,
  }

const AuthDashboardDirectRouteRouteWithChildren =
  AuthDashboardDirectRouteRoute._addFileChildren(
    AuthDashboardDirectRouteRouteChildren,
  )

interface AuthDashboardRouteRouteChildren {
  AuthDashboardApiRouteRoute: typeof AuthDashboardApiRouteRouteWithChildren
  AuthDashboardBindingRouteRoute: typeof AuthDashboardBindingRouteRouteWithChildren
  AuthDashboardDirectRouteRoute: typeof AuthDashboardDirectRouteRouteWithChildren
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
}

const AuthDashboardRouteRouteChildren: AuthDashboardRouteRouteChildren = {
  AuthDashboardApiRouteRoute: AuthDashboardApiRouteRouteWithChildren,
  AuthDashboardBindingRouteRoute: AuthDashboardBindingRouteRouteWithChildren,
  AuthDashboardDirectRouteRoute: AuthDashboardDirectRouteRouteWithChildren,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
}

const AuthDashboardRouteRouteWithChildren =
  AuthDashboardRouteRoute._addFileChildren(AuthDashboardRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthDashboardRouteRoute: typeof AuthDashboardRouteRouteWithChildren
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthDashboardRouteRoute: AuthDashboardRouteRouteWithChildren,
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
