/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteRouteImport } from './routes/demo/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoUsersListApiRouteImport } from './routes/demo/users-list-api'
import { Route as DemoUserDetailDirectRouteImport } from './routes/demo/user-detail-direct'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const DemoRouteRoute = DemoRouteRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoUsersListApiRoute = DemoUsersListApiRouteImport.update({
  id: '/users-list-api',
  path: '/users-list-api',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoUserDetailDirectRoute = DemoUserDetailDirectRouteImport.update({
  id: '/user-detail-direct',
  path: '/user-detail-direct',
  getParentRoute: () => DemoRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteRouteWithChildren
  '/demo/user-detail-direct': typeof DemoUserDetailDirectRoute
  '/demo/users-list-api': typeof DemoUsersListApiRoute
  '/demo/': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/user-detail-direct': typeof DemoUserDetailDirectRoute
  '/demo/users-list-api': typeof DemoUsersListApiRoute
  '/demo': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/demo': typeof DemoRouteRouteWithChildren
  '/demo/user-detail-direct': typeof DemoUserDetailDirectRoute
  '/demo/users-list-api': typeof DemoUsersListApiRoute
  '/demo/': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/demo/user-detail-direct'
    | '/demo/users-list-api'
    | '/demo/'
    | '/api/auth/$'
    | '/app'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/user-detail-direct'
    | '/demo/users-list-api'
    | '/demo'
    | '/api/auth/$'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/demo'
    | '/demo/user-detail-direct'
    | '/demo/users-list-api'
    | '/demo/'
    | '/api/auth/$'
    | '/_auth/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DemoRouteRoute: typeof DemoRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/users-list-api': {
      id: '/demo/users-list-api'
      path: '/users-list-api'
      fullPath: '/demo/users-list-api'
      preLoaderRoute: typeof DemoUsersListApiRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/user-detail-direct': {
      id: '/demo/user-detail-direct'
      path: '/user-detail-direct'
      fullPath: '/demo/user-detail-direct'
      preLoaderRoute: typeof DemoUserDetailDirectRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DemoRouteRouteChildren {
  DemoUserDetailDirectRoute: typeof DemoUserDetailDirectRoute
  DemoUsersListApiRoute: typeof DemoUsersListApiRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteRouteChildren: DemoRouteRouteChildren = {
  DemoUserDetailDirectRoute: DemoUserDetailDirectRoute,
  DemoUsersListApiRoute: DemoUsersListApiRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteRouteWithChildren = DemoRouteRoute._addFileChildren(
  DemoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DemoRouteRoute: DemoRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
